// Code generated by protoc-gen-go. DO NOT EDIT.
// source: submarineswaprpc/submarineswap.proto

package submarineswaprpc // import "github.com/lightningnetwork/lnd/lnrpc/submarineswaprpc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SubSwapClientInitRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubSwapClientInitRequest) Reset()         { *m = SubSwapClientInitRequest{} }
func (m *SubSwapClientInitRequest) String() string { return proto.CompactTextString(m) }
func (*SubSwapClientInitRequest) ProtoMessage()    {}
func (*SubSwapClientInitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_submarineswap_c0d3189a48a46e87, []int{0}
}
func (m *SubSwapClientInitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubSwapClientInitRequest.Unmarshal(m, b)
}
func (m *SubSwapClientInitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubSwapClientInitRequest.Marshal(b, m, deterministic)
}
func (dst *SubSwapClientInitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubSwapClientInitRequest.Merge(dst, src)
}
func (m *SubSwapClientInitRequest) XXX_Size() int {
	return xxx_messageInfo_SubSwapClientInitRequest.Size(m)
}
func (m *SubSwapClientInitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubSwapClientInitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubSwapClientInitRequest proto.InternalMessageInfo

type SubSwapClientInitResponse struct {
	Preimage             []byte   `protobuf:"bytes,1,opt,name=preimage,proto3" json:"preimage,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Key                  []byte   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Pubkey               []byte   `protobuf:"bytes,4,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubSwapClientInitResponse) Reset()         { *m = SubSwapClientInitResponse{} }
func (m *SubSwapClientInitResponse) String() string { return proto.CompactTextString(m) }
func (*SubSwapClientInitResponse) ProtoMessage()    {}
func (*SubSwapClientInitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_submarineswap_c0d3189a48a46e87, []int{1}
}
func (m *SubSwapClientInitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubSwapClientInitResponse.Unmarshal(m, b)
}
func (m *SubSwapClientInitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubSwapClientInitResponse.Marshal(b, m, deterministic)
}
func (dst *SubSwapClientInitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubSwapClientInitResponse.Merge(dst, src)
}
func (m *SubSwapClientInitResponse) XXX_Size() int {
	return xxx_messageInfo_SubSwapClientInitResponse.Size(m)
}
func (m *SubSwapClientInitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubSwapClientInitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubSwapClientInitResponse proto.InternalMessageInfo

func (m *SubSwapClientInitResponse) GetPreimage() []byte {
	if m != nil {
		return m.Preimage
	}
	return nil
}

func (m *SubSwapClientInitResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *SubSwapClientInitResponse) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SubSwapClientInitResponse) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

type SubSwapServiceInitRequest struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Pubkey               []byte   `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubSwapServiceInitRequest) Reset()         { *m = SubSwapServiceInitRequest{} }
func (m *SubSwapServiceInitRequest) String() string { return proto.CompactTextString(m) }
func (*SubSwapServiceInitRequest) ProtoMessage()    {}
func (*SubSwapServiceInitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_submarineswap_c0d3189a48a46e87, []int{2}
}
func (m *SubSwapServiceInitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubSwapServiceInitRequest.Unmarshal(m, b)
}
func (m *SubSwapServiceInitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubSwapServiceInitRequest.Marshal(b, m, deterministic)
}
func (dst *SubSwapServiceInitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubSwapServiceInitRequest.Merge(dst, src)
}
func (m *SubSwapServiceInitRequest) XXX_Size() int {
	return xxx_messageInfo_SubSwapServiceInitRequest.Size(m)
}
func (m *SubSwapServiceInitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubSwapServiceInitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubSwapServiceInitRequest proto.InternalMessageInfo

func (m *SubSwapServiceInitRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *SubSwapServiceInitRequest) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

type SubSwapServiceInitResponse struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Pubkey               []byte   `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	LockHeight           int64    `protobuf:"varint,3,opt,name=lock_height,proto3" json:"lock_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubSwapServiceInitResponse) Reset()         { *m = SubSwapServiceInitResponse{} }
func (m *SubSwapServiceInitResponse) String() string { return proto.CompactTextString(m) }
func (*SubSwapServiceInitResponse) ProtoMessage()    {}
func (*SubSwapServiceInitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_submarineswap_c0d3189a48a46e87, []int{3}
}
func (m *SubSwapServiceInitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubSwapServiceInitResponse.Unmarshal(m, b)
}
func (m *SubSwapServiceInitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubSwapServiceInitResponse.Marshal(b, m, deterministic)
}
func (dst *SubSwapServiceInitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubSwapServiceInitResponse.Merge(dst, src)
}
func (m *SubSwapServiceInitResponse) XXX_Size() int {
	return xxx_messageInfo_SubSwapServiceInitResponse.Size(m)
}
func (m *SubSwapServiceInitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubSwapServiceInitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubSwapServiceInitResponse proto.InternalMessageInfo

func (m *SubSwapServiceInitResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SubSwapServiceInitResponse) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *SubSwapServiceInitResponse) GetLockHeight() int64 {
	if m != nil {
		return m.LockHeight
	}
	return 0
}

type SubSwapClientWatchRequest struct {
	Preimage             []byte   `protobuf:"bytes,1,opt,name=preimage,proto3" json:"preimage,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ServicePubkey        []byte   `protobuf:"bytes,3,opt,name=service_pubkey,proto3" json:"service_pubkey,omitempty"`
	LockHeight           int64    `protobuf:"varint,4,opt,name=lock_height,proto3" json:"lock_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubSwapClientWatchRequest) Reset()         { *m = SubSwapClientWatchRequest{} }
func (m *SubSwapClientWatchRequest) String() string { return proto.CompactTextString(m) }
func (*SubSwapClientWatchRequest) ProtoMessage()    {}
func (*SubSwapClientWatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_submarineswap_c0d3189a48a46e87, []int{4}
}
func (m *SubSwapClientWatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubSwapClientWatchRequest.Unmarshal(m, b)
}
func (m *SubSwapClientWatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubSwapClientWatchRequest.Marshal(b, m, deterministic)
}
func (dst *SubSwapClientWatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubSwapClientWatchRequest.Merge(dst, src)
}
func (m *SubSwapClientWatchRequest) XXX_Size() int {
	return xxx_messageInfo_SubSwapClientWatchRequest.Size(m)
}
func (m *SubSwapClientWatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubSwapClientWatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubSwapClientWatchRequest proto.InternalMessageInfo

func (m *SubSwapClientWatchRequest) GetPreimage() []byte {
	if m != nil {
		return m.Preimage
	}
	return nil
}

func (m *SubSwapClientWatchRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SubSwapClientWatchRequest) GetServicePubkey() []byte {
	if m != nil {
		return m.ServicePubkey
	}
	return nil
}

func (m *SubSwapClientWatchRequest) GetLockHeight() int64 {
	if m != nil {
		return m.LockHeight
	}
	return 0
}

type SubSwapClientWatchResponse struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Script               []byte   `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubSwapClientWatchResponse) Reset()         { *m = SubSwapClientWatchResponse{} }
func (m *SubSwapClientWatchResponse) String() string { return proto.CompactTextString(m) }
func (*SubSwapClientWatchResponse) ProtoMessage()    {}
func (*SubSwapClientWatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_submarineswap_c0d3189a48a46e87, []int{5}
}
func (m *SubSwapClientWatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubSwapClientWatchResponse.Unmarshal(m, b)
}
func (m *SubSwapClientWatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubSwapClientWatchResponse.Marshal(b, m, deterministic)
}
func (dst *SubSwapClientWatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubSwapClientWatchResponse.Merge(dst, src)
}
func (m *SubSwapClientWatchResponse) XXX_Size() int {
	return xxx_messageInfo_SubSwapClientWatchResponse.Size(m)
}
func (m *SubSwapClientWatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubSwapClientWatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubSwapClientWatchResponse proto.InternalMessageInfo

func (m *SubSwapClientWatchResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SubSwapClientWatchResponse) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

type UnspentAmountRequest struct {
	// / The address (to be used by a client using swap service)
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// / The hash (to be used by a swapper service)
	Hash                 []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnspentAmountRequest) Reset()         { *m = UnspentAmountRequest{} }
func (m *UnspentAmountRequest) String() string { return proto.CompactTextString(m) }
func (*UnspentAmountRequest) ProtoMessage()    {}
func (*UnspentAmountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_submarineswap_c0d3189a48a46e87, []int{6}
}
func (m *UnspentAmountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnspentAmountRequest.Unmarshal(m, b)
}
func (m *UnspentAmountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnspentAmountRequest.Marshal(b, m, deterministic)
}
func (dst *UnspentAmountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnspentAmountRequest.Merge(dst, src)
}
func (m *UnspentAmountRequest) XXX_Size() int {
	return xxx_messageInfo_UnspentAmountRequest.Size(m)
}
func (m *UnspentAmountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnspentAmountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnspentAmountRequest proto.InternalMessageInfo

func (m *UnspentAmountRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UnspentAmountRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type UnspentAmountResponse struct {
	// / The total amount
	Amount               int64                         `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	LockHeight           int32                         `protobuf:"varint,2,opt,name=lock_height,proto3" json:"lock_height,omitempty"`
	Utxos                []*UnspentAmountResponse_Utxo `protobuf:"bytes,3,rep,name=utxos,proto3" json:"utxos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *UnspentAmountResponse) Reset()         { *m = UnspentAmountResponse{} }
func (m *UnspentAmountResponse) String() string { return proto.CompactTextString(m) }
func (*UnspentAmountResponse) ProtoMessage()    {}
func (*UnspentAmountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_submarineswap_c0d3189a48a46e87, []int{7}
}
func (m *UnspentAmountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnspentAmountResponse.Unmarshal(m, b)
}
func (m *UnspentAmountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnspentAmountResponse.Marshal(b, m, deterministic)
}
func (dst *UnspentAmountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnspentAmountResponse.Merge(dst, src)
}
func (m *UnspentAmountResponse) XXX_Size() int {
	return xxx_messageInfo_UnspentAmountResponse.Size(m)
}
func (m *UnspentAmountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnspentAmountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnspentAmountResponse proto.InternalMessageInfo

func (m *UnspentAmountResponse) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *UnspentAmountResponse) GetLockHeight() int32 {
	if m != nil {
		return m.LockHeight
	}
	return 0
}

func (m *UnspentAmountResponse) GetUtxos() []*UnspentAmountResponse_Utxo {
	if m != nil {
		return m.Utxos
	}
	return nil
}

type UnspentAmountResponse_Utxo struct {
	BlockHeight          int32    `protobuf:"varint,1,opt,name=block_height,proto3" json:"block_height,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Txid                 string   `protobuf:"bytes,3,opt,name=txid,proto3" json:"txid,omitempty"`
	Index                uint32   `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnspentAmountResponse_Utxo) Reset()         { *m = UnspentAmountResponse_Utxo{} }
func (m *UnspentAmountResponse_Utxo) String() string { return proto.CompactTextString(m) }
func (*UnspentAmountResponse_Utxo) ProtoMessage()    {}
func (*UnspentAmountResponse_Utxo) Descriptor() ([]byte, []int) {
	return fileDescriptor_submarineswap_c0d3189a48a46e87, []int{7, 0}
}
func (m *UnspentAmountResponse_Utxo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnspentAmountResponse_Utxo.Unmarshal(m, b)
}
func (m *UnspentAmountResponse_Utxo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnspentAmountResponse_Utxo.Marshal(b, m, deterministic)
}
func (dst *UnspentAmountResponse_Utxo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnspentAmountResponse_Utxo.Merge(dst, src)
}
func (m *UnspentAmountResponse_Utxo) XXX_Size() int {
	return xxx_messageInfo_UnspentAmountResponse_Utxo.Size(m)
}
func (m *UnspentAmountResponse_Utxo) XXX_DiscardUnknown() {
	xxx_messageInfo_UnspentAmountResponse_Utxo.DiscardUnknown(m)
}

var xxx_messageInfo_UnspentAmountResponse_Utxo proto.InternalMessageInfo

func (m *UnspentAmountResponse_Utxo) GetBlockHeight() int32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *UnspentAmountResponse_Utxo) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *UnspentAmountResponse_Utxo) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *UnspentAmountResponse_Utxo) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type SubSwapServiceRedeemFeesRequest struct {
	// / The hash (to be used by a swapper service)
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// / The target number of blocks that the funding transaction should be confirmed by.
	TargetConf int32 `protobuf:"varint,2,opt,name=target_conf,json=targetConf,proto3" json:"target_conf,omitempty"`
	// / A manual fee rate set in sat/byte that should be used when crafting the funding transaction.
	SatPerByte           int64    `protobuf:"varint,3,opt,name=sat_per_byte,json=satPerByte,proto3" json:"sat_per_byte,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubSwapServiceRedeemFeesRequest) Reset()         { *m = SubSwapServiceRedeemFeesRequest{} }
func (m *SubSwapServiceRedeemFeesRequest) String() string { return proto.CompactTextString(m) }
func (*SubSwapServiceRedeemFeesRequest) ProtoMessage()    {}
func (*SubSwapServiceRedeemFeesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_submarineswap_c0d3189a48a46e87, []int{8}
}
func (m *SubSwapServiceRedeemFeesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubSwapServiceRedeemFeesRequest.Unmarshal(m, b)
}
func (m *SubSwapServiceRedeemFeesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubSwapServiceRedeemFeesRequest.Marshal(b, m, deterministic)
}
func (dst *SubSwapServiceRedeemFeesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubSwapServiceRedeemFeesRequest.Merge(dst, src)
}
func (m *SubSwapServiceRedeemFeesRequest) XXX_Size() int {
	return xxx_messageInfo_SubSwapServiceRedeemFeesRequest.Size(m)
}
func (m *SubSwapServiceRedeemFeesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubSwapServiceRedeemFeesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubSwapServiceRedeemFeesRequest proto.InternalMessageInfo

func (m *SubSwapServiceRedeemFeesRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *SubSwapServiceRedeemFeesRequest) GetTargetConf() int32 {
	if m != nil {
		return m.TargetConf
	}
	return 0
}

func (m *SubSwapServiceRedeemFeesRequest) GetSatPerByte() int64 {
	if m != nil {
		return m.SatPerByte
	}
	return 0
}

type SubSwapServiceRedeemFeesResponse struct {
	Amount               int64    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubSwapServiceRedeemFeesResponse) Reset()         { *m = SubSwapServiceRedeemFeesResponse{} }
func (m *SubSwapServiceRedeemFeesResponse) String() string { return proto.CompactTextString(m) }
func (*SubSwapServiceRedeemFeesResponse) ProtoMessage()    {}
func (*SubSwapServiceRedeemFeesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_submarineswap_c0d3189a48a46e87, []int{9}
}
func (m *SubSwapServiceRedeemFeesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubSwapServiceRedeemFeesResponse.Unmarshal(m, b)
}
func (m *SubSwapServiceRedeemFeesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubSwapServiceRedeemFeesResponse.Marshal(b, m, deterministic)
}
func (dst *SubSwapServiceRedeemFeesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubSwapServiceRedeemFeesResponse.Merge(dst, src)
}
func (m *SubSwapServiceRedeemFeesResponse) XXX_Size() int {
	return xxx_messageInfo_SubSwapServiceRedeemFeesResponse.Size(m)
}
func (m *SubSwapServiceRedeemFeesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubSwapServiceRedeemFeesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubSwapServiceRedeemFeesResponse proto.InternalMessageInfo

func (m *SubSwapServiceRedeemFeesResponse) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type SubSwapServiceRedeemRequest struct {
	Preimage []byte `protobuf:"bytes,1,opt,name=preimage,proto3" json:"preimage,omitempty"`
	// / The target number of blocks that the funding transaction should be confirmed by.
	TargetConf int32 `protobuf:"varint,2,opt,name=target_conf,json=targetConf,proto3" json:"target_conf,omitempty"`
	// / A manual fee rate set in sat/byte that should be used when crafting the funding transaction.
	SatPerByte           int64    `protobuf:"varint,3,opt,name=sat_per_byte,json=satPerByte,proto3" json:"sat_per_byte,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubSwapServiceRedeemRequest) Reset()         { *m = SubSwapServiceRedeemRequest{} }
func (m *SubSwapServiceRedeemRequest) String() string { return proto.CompactTextString(m) }
func (*SubSwapServiceRedeemRequest) ProtoMessage()    {}
func (*SubSwapServiceRedeemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_submarineswap_c0d3189a48a46e87, []int{10}
}
func (m *SubSwapServiceRedeemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubSwapServiceRedeemRequest.Unmarshal(m, b)
}
func (m *SubSwapServiceRedeemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubSwapServiceRedeemRequest.Marshal(b, m, deterministic)
}
func (dst *SubSwapServiceRedeemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubSwapServiceRedeemRequest.Merge(dst, src)
}
func (m *SubSwapServiceRedeemRequest) XXX_Size() int {
	return xxx_messageInfo_SubSwapServiceRedeemRequest.Size(m)
}
func (m *SubSwapServiceRedeemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubSwapServiceRedeemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubSwapServiceRedeemRequest proto.InternalMessageInfo

func (m *SubSwapServiceRedeemRequest) GetPreimage() []byte {
	if m != nil {
		return m.Preimage
	}
	return nil
}

func (m *SubSwapServiceRedeemRequest) GetTargetConf() int32 {
	if m != nil {
		return m.TargetConf
	}
	return 0
}

func (m *SubSwapServiceRedeemRequest) GetSatPerByte() int64 {
	if m != nil {
		return m.SatPerByte
	}
	return 0
}

type SubSwapServiceRedeemResponse struct {
	// / The txid of the transaction.
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubSwapServiceRedeemResponse) Reset()         { *m = SubSwapServiceRedeemResponse{} }
func (m *SubSwapServiceRedeemResponse) String() string { return proto.CompactTextString(m) }
func (*SubSwapServiceRedeemResponse) ProtoMessage()    {}
func (*SubSwapServiceRedeemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_submarineswap_c0d3189a48a46e87, []int{11}
}
func (m *SubSwapServiceRedeemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubSwapServiceRedeemResponse.Unmarshal(m, b)
}
func (m *SubSwapServiceRedeemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubSwapServiceRedeemResponse.Marshal(b, m, deterministic)
}
func (dst *SubSwapServiceRedeemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubSwapServiceRedeemResponse.Merge(dst, src)
}
func (m *SubSwapServiceRedeemResponse) XXX_Size() int {
	return xxx_messageInfo_SubSwapServiceRedeemResponse.Size(m)
}
func (m *SubSwapServiceRedeemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubSwapServiceRedeemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubSwapServiceRedeemResponse proto.InternalMessageInfo

func (m *SubSwapServiceRedeemResponse) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type SubSwapClientRefundRequest struct {
	// / The address used for the swap.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// / The address to receive the refund.
	RefundAddress string `protobuf:"bytes,2,opt,name=refundAddress,json=refund_address,proto3" json:"refundAddress,omitempty"`
	// / The target number of blocks that the funding transaction should be confirmed by.
	TargetConf int32 `protobuf:"varint,3,opt,name=target_conf,json=targetConf,proto3" json:"target_conf,omitempty"`
	// / A manual fee rate set in sat/byte that should be used when crafting the funding transaction.
	SatPerByte           int64    `protobuf:"varint,4,opt,name=sat_per_byte,json=satPerByte,proto3" json:"sat_per_byte,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubSwapClientRefundRequest) Reset()         { *m = SubSwapClientRefundRequest{} }
func (m *SubSwapClientRefundRequest) String() string { return proto.CompactTextString(m) }
func (*SubSwapClientRefundRequest) ProtoMessage()    {}
func (*SubSwapClientRefundRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_submarineswap_c0d3189a48a46e87, []int{12}
}
func (m *SubSwapClientRefundRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubSwapClientRefundRequest.Unmarshal(m, b)
}
func (m *SubSwapClientRefundRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubSwapClientRefundRequest.Marshal(b, m, deterministic)
}
func (dst *SubSwapClientRefundRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubSwapClientRefundRequest.Merge(dst, src)
}
func (m *SubSwapClientRefundRequest) XXX_Size() int {
	return xxx_messageInfo_SubSwapClientRefundRequest.Size(m)
}
func (m *SubSwapClientRefundRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubSwapClientRefundRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubSwapClientRefundRequest proto.InternalMessageInfo

func (m *SubSwapClientRefundRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SubSwapClientRefundRequest) GetRefundAddress() string {
	if m != nil {
		return m.RefundAddress
	}
	return ""
}

func (m *SubSwapClientRefundRequest) GetTargetConf() int32 {
	if m != nil {
		return m.TargetConf
	}
	return 0
}

func (m *SubSwapClientRefundRequest) GetSatPerByte() int64 {
	if m != nil {
		return m.SatPerByte
	}
	return 0
}

type SubSwapClientRefundResponse struct {
	// / The txid of the transaction.
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubSwapClientRefundResponse) Reset()         { *m = SubSwapClientRefundResponse{} }
func (m *SubSwapClientRefundResponse) String() string { return proto.CompactTextString(m) }
func (*SubSwapClientRefundResponse) ProtoMessage()    {}
func (*SubSwapClientRefundResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_submarineswap_c0d3189a48a46e87, []int{13}
}
func (m *SubSwapClientRefundResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubSwapClientRefundResponse.Unmarshal(m, b)
}
func (m *SubSwapClientRefundResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubSwapClientRefundResponse.Marshal(b, m, deterministic)
}
func (dst *SubSwapClientRefundResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubSwapClientRefundResponse.Merge(dst, src)
}
func (m *SubSwapClientRefundResponse) XXX_Size() int {
	return xxx_messageInfo_SubSwapClientRefundResponse.Size(m)
}
func (m *SubSwapClientRefundResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubSwapClientRefundResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubSwapClientRefundResponse proto.InternalMessageInfo

func (m *SubSwapClientRefundResponse) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func init() {
	proto.RegisterType((*SubSwapClientInitRequest)(nil), "submarineswaprpc.SubSwapClientInitRequest")
	proto.RegisterType((*SubSwapClientInitResponse)(nil), "submarineswaprpc.SubSwapClientInitResponse")
	proto.RegisterType((*SubSwapServiceInitRequest)(nil), "submarineswaprpc.SubSwapServiceInitRequest")
	proto.RegisterType((*SubSwapServiceInitResponse)(nil), "submarineswaprpc.SubSwapServiceInitResponse")
	proto.RegisterType((*SubSwapClientWatchRequest)(nil), "submarineswaprpc.SubSwapClientWatchRequest")
	proto.RegisterType((*SubSwapClientWatchResponse)(nil), "submarineswaprpc.SubSwapClientWatchResponse")
	proto.RegisterType((*UnspentAmountRequest)(nil), "submarineswaprpc.UnspentAmountRequest")
	proto.RegisterType((*UnspentAmountResponse)(nil), "submarineswaprpc.UnspentAmountResponse")
	proto.RegisterType((*UnspentAmountResponse_Utxo)(nil), "submarineswaprpc.UnspentAmountResponse.Utxo")
	proto.RegisterType((*SubSwapServiceRedeemFeesRequest)(nil), "submarineswaprpc.SubSwapServiceRedeemFeesRequest")
	proto.RegisterType((*SubSwapServiceRedeemFeesResponse)(nil), "submarineswaprpc.SubSwapServiceRedeemFeesResponse")
	proto.RegisterType((*SubSwapServiceRedeemRequest)(nil), "submarineswaprpc.SubSwapServiceRedeemRequest")
	proto.RegisterType((*SubSwapServiceRedeemResponse)(nil), "submarineswaprpc.SubSwapServiceRedeemResponse")
	proto.RegisterType((*SubSwapClientRefundRequest)(nil), "submarineswaprpc.SubSwapClientRefundRequest")
	proto.RegisterType((*SubSwapClientRefundResponse)(nil), "submarineswaprpc.SubSwapClientRefundResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SubmarineSwapperClient is the client API for SubmarineSwapper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SubmarineSwapperClient interface {
	SubSwapClientInit(ctx context.Context, in *SubSwapClientInitRequest, opts ...grpc.CallOption) (*SubSwapClientInitResponse, error)
	// *
	SubSwapServiceInit(ctx context.Context, in *SubSwapServiceInitRequest, opts ...grpc.CallOption) (*SubSwapServiceInitResponse, error)
	// *
	SubSwapClientWatch(ctx context.Context, in *SubSwapClientWatchRequest, opts ...grpc.CallOption) (*SubSwapClientWatchResponse, error)
	// *
	// UnspentAmount returns the total amount of the btc received in a watched address,
	// the block height and the age of the first transaction sending btc to the address.
	UnspentAmount(ctx context.Context, in *UnspentAmountRequest, opts ...grpc.CallOption) (*UnspentAmountResponse, error)
	// *
	// SubSwapServiceFeesRedeem returns the fees to redeem the amount received.
	SubSwapServiceRedeemFees(ctx context.Context, in *SubSwapServiceRedeemFeesRequest, opts ...grpc.CallOption) (*SubSwapServiceRedeemFeesResponse, error)
	// *
	// SubSwapServiceRedeem redeems the amount received to a new address of the internal wallet.
	SubSwapServiceRedeem(ctx context.Context, in *SubSwapServiceRedeemRequest, opts ...grpc.CallOption) (*SubSwapServiceRedeemResponse, error)
	// *
	// SubSwapClientRefund refunds the amount received to a an external address.
	SubSwapClientRefund(ctx context.Context, in *SubSwapClientRefundRequest, opts ...grpc.CallOption) (*SubSwapClientRefundResponse, error)
}

type submarineSwapperClient struct {
	cc *grpc.ClientConn
}

func NewSubmarineSwapperClient(cc *grpc.ClientConn) SubmarineSwapperClient {
	return &submarineSwapperClient{cc}
}

func (c *submarineSwapperClient) SubSwapClientInit(ctx context.Context, in *SubSwapClientInitRequest, opts ...grpc.CallOption) (*SubSwapClientInitResponse, error) {
	out := new(SubSwapClientInitResponse)
	err := c.cc.Invoke(ctx, "/submarineswaprpc.SubmarineSwapper/SubSwapClientInit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submarineSwapperClient) SubSwapServiceInit(ctx context.Context, in *SubSwapServiceInitRequest, opts ...grpc.CallOption) (*SubSwapServiceInitResponse, error) {
	out := new(SubSwapServiceInitResponse)
	err := c.cc.Invoke(ctx, "/submarineswaprpc.SubmarineSwapper/SubSwapServiceInit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submarineSwapperClient) SubSwapClientWatch(ctx context.Context, in *SubSwapClientWatchRequest, opts ...grpc.CallOption) (*SubSwapClientWatchResponse, error) {
	out := new(SubSwapClientWatchResponse)
	err := c.cc.Invoke(ctx, "/submarineswaprpc.SubmarineSwapper/SubSwapClientWatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submarineSwapperClient) UnspentAmount(ctx context.Context, in *UnspentAmountRequest, opts ...grpc.CallOption) (*UnspentAmountResponse, error) {
	out := new(UnspentAmountResponse)
	err := c.cc.Invoke(ctx, "/submarineswaprpc.SubmarineSwapper/UnspentAmount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submarineSwapperClient) SubSwapServiceRedeemFees(ctx context.Context, in *SubSwapServiceRedeemFeesRequest, opts ...grpc.CallOption) (*SubSwapServiceRedeemFeesResponse, error) {
	out := new(SubSwapServiceRedeemFeesResponse)
	err := c.cc.Invoke(ctx, "/submarineswaprpc.SubmarineSwapper/SubSwapServiceRedeemFees", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submarineSwapperClient) SubSwapServiceRedeem(ctx context.Context, in *SubSwapServiceRedeemRequest, opts ...grpc.CallOption) (*SubSwapServiceRedeemResponse, error) {
	out := new(SubSwapServiceRedeemResponse)
	err := c.cc.Invoke(ctx, "/submarineswaprpc.SubmarineSwapper/SubSwapServiceRedeem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submarineSwapperClient) SubSwapClientRefund(ctx context.Context, in *SubSwapClientRefundRequest, opts ...grpc.CallOption) (*SubSwapClientRefundResponse, error) {
	out := new(SubSwapClientRefundResponse)
	err := c.cc.Invoke(ctx, "/submarineswaprpc.SubmarineSwapper/SubSwapClientRefund", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubmarineSwapperServer is the server API for SubmarineSwapper service.
type SubmarineSwapperServer interface {
	SubSwapClientInit(context.Context, *SubSwapClientInitRequest) (*SubSwapClientInitResponse, error)
	// *
	SubSwapServiceInit(context.Context, *SubSwapServiceInitRequest) (*SubSwapServiceInitResponse, error)
	// *
	SubSwapClientWatch(context.Context, *SubSwapClientWatchRequest) (*SubSwapClientWatchResponse, error)
	// *
	// UnspentAmount returns the total amount of the btc received in a watched address,
	// the block height and the age of the first transaction sending btc to the address.
	UnspentAmount(context.Context, *UnspentAmountRequest) (*UnspentAmountResponse, error)
	// *
	// SubSwapServiceFeesRedeem returns the fees to redeem the amount received.
	SubSwapServiceRedeemFees(context.Context, *SubSwapServiceRedeemFeesRequest) (*SubSwapServiceRedeemFeesResponse, error)
	// *
	// SubSwapServiceRedeem redeems the amount received to a new address of the internal wallet.
	SubSwapServiceRedeem(context.Context, *SubSwapServiceRedeemRequest) (*SubSwapServiceRedeemResponse, error)
	// *
	// SubSwapClientRefund refunds the amount received to a an external address.
	SubSwapClientRefund(context.Context, *SubSwapClientRefundRequest) (*SubSwapClientRefundResponse, error)
}

func RegisterSubmarineSwapperServer(s *grpc.Server, srv SubmarineSwapperServer) {
	s.RegisterService(&_SubmarineSwapper_serviceDesc, srv)
}

func _SubmarineSwapper_SubSwapClientInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubSwapClientInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmarineSwapperServer).SubSwapClientInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/submarineswaprpc.SubmarineSwapper/SubSwapClientInit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmarineSwapperServer).SubSwapClientInit(ctx, req.(*SubSwapClientInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubmarineSwapper_SubSwapServiceInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubSwapServiceInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmarineSwapperServer).SubSwapServiceInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/submarineswaprpc.SubmarineSwapper/SubSwapServiceInit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmarineSwapperServer).SubSwapServiceInit(ctx, req.(*SubSwapServiceInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubmarineSwapper_SubSwapClientWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubSwapClientWatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmarineSwapperServer).SubSwapClientWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/submarineswaprpc.SubmarineSwapper/SubSwapClientWatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmarineSwapperServer).SubSwapClientWatch(ctx, req.(*SubSwapClientWatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubmarineSwapper_UnspentAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnspentAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmarineSwapperServer).UnspentAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/submarineswaprpc.SubmarineSwapper/UnspentAmount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmarineSwapperServer).UnspentAmount(ctx, req.(*UnspentAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubmarineSwapper_SubSwapServiceRedeemFees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubSwapServiceRedeemFeesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmarineSwapperServer).SubSwapServiceRedeemFees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/submarineswaprpc.SubmarineSwapper/SubSwapServiceRedeemFees",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmarineSwapperServer).SubSwapServiceRedeemFees(ctx, req.(*SubSwapServiceRedeemFeesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubmarineSwapper_SubSwapServiceRedeem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubSwapServiceRedeemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmarineSwapperServer).SubSwapServiceRedeem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/submarineswaprpc.SubmarineSwapper/SubSwapServiceRedeem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmarineSwapperServer).SubSwapServiceRedeem(ctx, req.(*SubSwapServiceRedeemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubmarineSwapper_SubSwapClientRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubSwapClientRefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmarineSwapperServer).SubSwapClientRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/submarineswaprpc.SubmarineSwapper/SubSwapClientRefund",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmarineSwapperServer).SubSwapClientRefund(ctx, req.(*SubSwapClientRefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SubmarineSwapper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "submarineswaprpc.SubmarineSwapper",
	HandlerType: (*SubmarineSwapperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubSwapClientInit",
			Handler:    _SubmarineSwapper_SubSwapClientInit_Handler,
		},
		{
			MethodName: "SubSwapServiceInit",
			Handler:    _SubmarineSwapper_SubSwapServiceInit_Handler,
		},
		{
			MethodName: "SubSwapClientWatch",
			Handler:    _SubmarineSwapper_SubSwapClientWatch_Handler,
		},
		{
			MethodName: "UnspentAmount",
			Handler:    _SubmarineSwapper_UnspentAmount_Handler,
		},
		{
			MethodName: "SubSwapServiceRedeemFees",
			Handler:    _SubmarineSwapper_SubSwapServiceRedeemFees_Handler,
		},
		{
			MethodName: "SubSwapServiceRedeem",
			Handler:    _SubmarineSwapper_SubSwapServiceRedeem_Handler,
		},
		{
			MethodName: "SubSwapClientRefund",
			Handler:    _SubmarineSwapper_SubSwapClientRefund_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "submarineswaprpc/submarineswap.proto",
}

func init() {
	proto.RegisterFile("submarineswaprpc/submarineswap.proto", fileDescriptor_submarineswap_c0d3189a48a46e87)
}

var fileDescriptor_submarineswap_c0d3189a48a46e87 = []byte{
	// 718 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0xae, 0x93, 0x34, 0xff, 0xdf, 0xe9, 0x41, 0x65, 0x29, 0x55, 0x30, 0x48, 0x8d, 0x56, 0x50,
	0x2a, 0x68, 0x13, 0x35, 0x48, 0x08, 0x71, 0xd7, 0x16, 0x81, 0xb8, 0x41, 0xc8, 0x51, 0x85, 0xc4,
	0x4d, 0xe4, 0xc3, 0x34, 0xb1, 0x9a, 0xac, 0xdd, 0xdd, 0x35, 0x49, 0x25, 0xee, 0xfa, 0x08, 0xbc,
	0x00, 0xaf, 0xc2, 0x9b, 0xa1, 0xac, 0x0f, 0xf5, 0x29, 0x89, 0x91, 0xb8, 0xdb, 0x99, 0x9d, 0xfd,
	0xe6, 0x9b, 0x6f, 0x67, 0xc7, 0x86, 0x67, 0x22, 0xb0, 0x26, 0x26, 0x77, 0x19, 0x8a, 0xa9, 0xe9,
	0x73, 0xdf, 0xee, 0x66, 0x1c, 0x1d, 0x9f, 0x7b, 0xd2, 0x23, 0xbb, 0xf9, 0x28, 0xaa, 0x43, 0xab,
	0x1f, 0x58, 0xfd, 0xa9, 0xe9, 0x5f, 0x8c, 0x5d, 0x64, 0xf2, 0x13, 0x73, 0xa5, 0x81, 0x37, 0x01,
	0x0a, 0x49, 0x03, 0x78, 0x5c, 0xb2, 0x27, 0x7c, 0x8f, 0x09, 0x24, 0x3a, 0xfc, 0xef, 0x73, 0x74,
	0x27, 0xe6, 0x10, 0x5b, 0x5a, 0x5b, 0x3b, 0xda, 0x32, 0x12, 0x9b, 0x10, 0x68, 0x8c, 0x4c, 0x31,
	0x6a, 0xd5, 0x94, 0x5f, 0xad, 0xc9, 0x2e, 0xd4, 0xaf, 0xf1, 0xb6, 0x55, 0x57, 0xae, 0xf9, 0x92,
	0xec, 0x43, 0xd3, 0x0f, 0xac, 0xb9, 0xb3, 0xa1, 0x9c, 0x91, 0x45, 0x3f, 0x26, 0x69, 0xfb, 0xc8,
	0xbf, 0xbb, 0x36, 0xa6, 0x38, 0x25, 0xd0, 0x5a, 0x0a, 0xfa, 0x1e, 0xa8, 0x96, 0x01, 0xf2, 0x41,
	0x2f, 0x03, 0x8a, 0x0a, 0x68, 0xc1, 0x7f, 0xa6, 0xe3, 0x70, 0x14, 0x42, 0x81, 0x6d, 0x18, 0xb1,
	0xb9, 0x08, 0x8f, 0xb4, 0x61, 0x73, 0xec, 0xd9, 0xd7, 0x83, 0x11, 0xba, 0xc3, 0x91, 0x54, 0xa5,
	0xd4, 0x8d, 0xb4, 0x8b, 0xfe, 0xd4, 0x72, 0x92, 0x7d, 0x35, 0xa5, 0x3d, 0x8a, 0xb9, 0x2f, 0x93,
	0x2c, 0x92, 0xa7, 0x76, 0x2f, 0xcf, 0x21, 0xec, 0x88, 0x90, 0xf6, 0x20, 0x62, 0x13, 0x6a, 0x97,
	0xf3, 0xe6, 0x59, 0x35, 0x8a, 0xac, 0x3e, 0x27, 0x3a, 0x64, 0x48, 0x55, 0xd1, 0x41, 0xd8, 0xdc,
	0xf5, 0x65, 0xac, 0x43, 0x68, 0xd1, 0xf7, 0xb0, 0x77, 0xc9, 0x84, 0x8f, 0x4c, 0x9e, 0x4d, 0xbc,
	0x80, 0x25, 0x77, 0xb3, 0x18, 0xa9, 0xa4, 0x21, 0xe8, 0x5d, 0x0d, 0x1e, 0xe5, 0x60, 0x22, 0x46,
	0xfb, 0xd0, 0x34, 0x95, 0x47, 0xc1, 0xd4, 0x8d, 0xc8, 0xca, 0x57, 0x3a, 0x07, 0x5b, 0xcf, 0x54,
	0x4a, 0xce, 0x61, 0x3d, 0x90, 0x33, 0x4f, 0xb4, 0xea, 0xed, 0xfa, 0xd1, 0x66, 0xef, 0xb8, 0x93,
	0xef, 0xf7, 0x4e, 0x69, 0xc6, 0xce, 0xa5, 0x9c, 0x79, 0x46, 0x78, 0x54, 0x1f, 0x43, 0x63, 0x6e,
	0x12, 0x0a, 0x5b, 0x56, 0x3a, 0x9d, 0xa6, 0xd2, 0x65, 0x7c, 0x29, 0xa6, 0xb5, 0x0c, 0x53, 0x02,
	0x0d, 0x39, 0x73, 0x1d, 0x75, 0x63, 0x1b, 0x86, 0x5a, 0x93, 0x3d, 0x58, 0x77, 0x99, 0x83, 0x33,
	0x75, 0x43, 0xdb, 0x46, 0x68, 0xd0, 0x19, 0x1c, 0x64, 0x7b, 0xd4, 0x40, 0x07, 0x71, 0xf2, 0x01,
	0x51, 0x2c, 0x6b, 0xf9, 0x03, 0xd8, 0x94, 0x26, 0x1f, 0xa2, 0x1c, 0xd8, 0x1e, 0xbb, 0x8a, 0xa4,
	0x80, 0xd0, 0x75, 0xe1, 0xb1, 0x2b, 0xd2, 0x86, 0x2d, 0x61, 0xca, 0x81, 0x8f, 0x7c, 0x60, 0xdd,
	0x4a, 0x8c, 0x9a, 0x15, 0x84, 0x29, 0xbf, 0x20, 0x3f, 0xbf, 0x95, 0x48, 0xdf, 0x41, 0x7b, 0x71,
	0xe6, 0xe5, 0x37, 0x41, 0x7f, 0xc0, 0x93, 0xb2, 0xb3, 0x55, 0x1a, 0xfd, 0x1f, 0x30, 0xef, 0xc1,
	0xd3, 0xf2, 0xec, 0x11, 0xeb, 0x58, 0x7d, 0xed, 0x5e, 0x7d, 0xfa, 0x4b, 0xcb, 0x3d, 0x02, 0x03,
	0xaf, 0x02, 0xe6, 0xac, 0x6e, 0xdd, 0xe7, 0xb0, 0xcd, 0x55, 0xe8, 0x59, 0xb4, 0x5f, 0x53, 0xfb,
	0x3b, 0xa1, 0x73, 0x10, 0x87, 0xe5, 0xca, 0xaa, 0xaf, 0x2c, 0xab, 0x51, 0x28, 0xeb, 0x34, 0x11,
	0x35, 0xcb, 0x70, 0x71, 0x55, 0xbd, 0xdf, 0x4d, 0xd8, 0xed, 0xc7, 0x2d, 0x3e, 0x3f, 0xe9, 0x23,
	0x27, 0x0c, 0x1e, 0x14, 0xc6, 0x36, 0x79, 0x59, 0x7c, 0x0a, 0x8b, 0xe6, 0xbe, 0xfe, 0xaa, 0x52,
	0x6c, 0x48, 0x8b, 0xae, 0x91, 0x1b, 0x20, 0xc5, 0x31, 0x4b, 0x16, 0x83, 0x14, 0xa7, 0xba, 0x7e,
	0x5c, 0x2d, 0xb8, 0x24, 0x65, 0x6a, 0xa2, 0x91, 0x55, 0xbc, 0xd3, 0xc3, 0x78, 0x49, 0xca, 0x92,
	0x21, 0x49, 0xd7, 0x88, 0x05, 0xdb, 0x99, 0xd9, 0x41, 0x0e, 0x57, 0x0e, 0x97, 0x30, 0xd1, 0x8b,
	0x8a, 0x43, 0x88, 0xae, 0x91, 0x3b, 0x2d, 0xf9, 0x1a, 0x17, 0xde, 0x24, 0x39, 0x5d, 0xa5, 0x51,
	0x61, 0x72, 0xe8, 0xbd, 0xbf, 0x39, 0x92, 0xb0, 0x98, 0xc2, 0x5e, 0x59, 0x14, 0x39, 0xa9, 0x86,
	0x16, 0x27, 0xef, 0x54, 0x0d, 0x4f, 0x12, 0x4b, 0x78, 0x58, 0xf2, 0x00, 0xc8, 0xaa, 0x9b, 0xca,
	0xbc, 0x64, 0xfd, 0xa4, 0x62, 0x74, 0x9c, 0xf5, 0xfc, 0xed, 0xb7, 0x37, 0x43, 0x57, 0x8e, 0x02,
	0xab, 0x63, 0x7b, 0x93, 0xee, 0x78, 0x3e, 0xd7, 0x99, 0xcb, 0x86, 0x0c, 0xe5, 0xd4, 0xe3, 0xd7,
	0xdd, 0x31, 0x73, 0xba, 0x63, 0x56, 0xf8, 0xa1, 0xe2, 0xbe, 0x6d, 0x35, 0xd5, 0x4f, 0xd5, 0xeb,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x08, 0x67, 0xa3, 0xaf, 0x7c, 0x09, 0x00, 0x00,
}
